Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-24.04"
    config.vm.network "public_network", bridge: "en13: Belkin USB-C LAN"

    def configure_shared_vm(vm, name)
        vm.vm.box = "bento/ubuntu-24.04"
        vm.vm.hostname = name

        vm.vm.synced_folder "./shared_#{name}", "/home/vagrant/app"

        vm.vm.provision "shell", inline: <<-SHELL
          echo "=== #{name} provisioning ==="
          echo "=== HELLO FROM #{name} CONSOLE ==="
          pwd
          echo "HELLO FROM #{name} provisioning" >> /home/vagrant/app/hello.txt
        SHELL
    end

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false

        vb.memory = "1024"
        vb.cpus = "2"
    end

    config.vm.provision "nginx", type: "shell", inline: <<-SHELL
        sudo apt-get update -y
        sudo apt-get install -y nginx

        sudo systemctl enable nginx
        sudo systemctl start nginx
    SHELL

    config.vm.define "vm1" do |vm1|
        configure_shared_vm(vm1, "vm1")
    end

    config.vm.define "vm2" do |vm2|
        configure_shared_vm(vm2, "vm2")
    end

    config.vm.define "vm3" do |vm3|
        configure_shared_vm(vm3, "vm3")
    end
end

# Vagrant.configure("2") do |config|
#
#     config.vm.box = "bento/ubuntu-24.04"
#     config.vm.network "public_network", bridge: "en13: Belkin USB-C LAN"
#     config.vm.synced_folder "./shared_multiple", "/home/vagrant/app"
#     config.vm.provision "shell", path: "provision.sh"
#
#     config.vm.provider "virtualbox" do |vb|
#         # Display the VirtualBox GUI when booting the machine
#         vb.gui = false
#
#         # Customize the amount of memory on the VM:
#         vb.memory = "1024"
#         vb.cpus = "2"
#     end
#
#     config.vm.provision "nginx", type: "shell", inline: <<-SHELL
#         sudo apt-get update -y
#         sudo apt-get install -y nginx
#
#         sudo systemctl enable nginx
#         sudo systemctl start nginx
#     SHELL
#
#     config.vm.define "vm1" do |vm1|
#         vm1.vm.hostname = "public-server"
#     end
#
#     config.vm.define "vm2" do |vm2|
#         vm2.vm.hostname = "private-server"
#     end
#
#     config.vm.define "vm3" do |vm3|
#         vm3.vm.hostname = "public-static"
#     end
# end
