services:
  web:
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./web:/usr/share/nginx/html
    networks:
      - appnet

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - appnet

  cache:
    image: redis:7
    networks:
      - appnet

volumes:
  db-data:

networks:
  appnet:
    driver: bridge
